# Generated by Django 4.2.11 on 2024-04-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_userdetail_latitude_alter_userdetail_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=64)),
                ('city_name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('latitude', models.DateField(max_length=32)),
                ('longitude', models.DateField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Latitude',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Longitude',
            field=models.CharField(max_length=32),
        ),
    ]
