# Generated by Django 4.2.11 on 2024-04-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventdata_alter_userdetail_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='date',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='latitude',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='longitude',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Date',
            field=models.CharField(max_length=16),
        ),
    ]
