# Generated by Django 4.2.11 on 2024-04-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_eventdata_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdetail',
        ),
    ]
