# Generated by Django 4.2.11 on 2024-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_delete_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='date',
            field=models.DateField(),
        ),
    ]
